[2025-03-17 19:28:46,585] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T18:27:40.197027+00:00 [queued]>
[2025-03-17 19:28:46,593] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T18:27:40.197027+00:00 [queued]>
[2025-03-17 19:28:46,593] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 19:28:46,593] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2025-03-17 19:28:46,593] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 19:28:46,603] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_data> on 2025-03-17 18:27:40.197027+00:00
[2025-03-17 19:28:46,606] {standard_task_runner.py:52} INFO - Started process 88298 to run task
[2025-03-17 19:28:46,614] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'weather_ingestion', 'load_data', 'scheduled__2025-03-17T18:27:40.197027+00:00', '--job-id', '215', '--raw', '--subdir', '/Users/yellow/Desktop/data_engineering/airflow_weather_01/dags/dag_weather.py', '--cfg-path', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmp9o94ijqd', '--error-file', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmprcnni40h']
[2025-03-17 19:28:46,616] {standard_task_runner.py:77} INFO - Job 215: Subtask load_data
[2025-03-17 19:28:46,658] {logging_mixin.py:109} INFO - Running <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T18:27:40.197027+00:00 [running]> on host 147.0.168.192.in-addr.arpa
[2025-03-17 19:28:46,698] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=weather_ingestion
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2025-03-17T18:27:40.197027+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-17T18:27:40.197027+00:00
[2025-03-17 19:28:46,755] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-17 19:28:46,755] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-03-17 19:28:46,756] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-03-17 19:28:46,767] {python.py:152} INFO - Done. Returned value was: None
[2025-03-17 19:28:46,773] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=weather_ingestion, task_id=load_data, execution_date=20250317T182740, start_date=20250317T182846, end_date=20250317T182846
[2025-03-17 19:28:46,798] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-03-17 19:28:46,817] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
