[2025-03-17 19:06:01,769] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T18:04:54.924423+00:00 [queued]>
[2025-03-17 19:06:01,782] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T18:04:54.924423+00:00 [queued]>
[2025-03-17 19:06:01,782] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 19:06:01,782] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2025-03-17 19:06:01,782] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 19:06:01,798] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_data> on 2025-03-17 18:04:54.924423+00:00
[2025-03-17 19:06:01,802] {standard_task_runner.py:52} INFO - Started process 79741 to run task
[2025-03-17 19:06:01,808] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'weather_ingestion', 'load_data', 'scheduled__2025-03-17T18:04:54.924423+00:00', '--job-id', '171', '--raw', '--subdir', '/Users/yellow/Desktop/data_engineering/airflow_weather_01/dags/dag_weather.py', '--cfg-path', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmpuejx56ci', '--error-file', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmplelmscau']
[2025-03-17 19:06:01,812] {standard_task_runner.py:77} INFO - Job 171: Subtask load_data
[2025-03-17 19:06:01,854] {logging_mixin.py:109} INFO - Running <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T18:04:54.924423+00:00 [running]> on host 147.0.168.192.in-addr.arpa
[2025-03-17 19:06:01,907] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=weather_ingestion
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2025-03-17T18:04:54.924423+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-17T18:04:54.924423+00:00
[2025-03-17 19:06:01,969] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-17 19:06:01,969] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-03-17 19:06:01,970] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-03-17 19:06:01,982] {python.py:152} INFO - Done. Returned value was: None
[2025-03-17 19:06:01,988] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=weather_ingestion, task_id=load_data, execution_date=20250317T180454, start_date=20250317T180601, end_date=20250317T180601
[2025-03-17 19:06:02,042] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-03-17 19:06:02,064] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
