[2025-03-17 13:00:33,806] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T11:59:24.956227+00:00 [queued]>
[2025-03-17 13:00:33,813] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T11:59:24.956227+00:00 [queued]>
[2025-03-17 13:00:33,813] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 13:00:33,813] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2025-03-17 13:00:33,813] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 13:00:33,822] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_data> on 2025-03-17 11:59:24.956227+00:00
[2025-03-17 13:00:33,824] {standard_task_runner.py:52} INFO - Started process 26013 to run task
[2025-03-17 13:00:33,831] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'weather_ingestion', 'load_data', 'scheduled__2025-03-17T11:59:24.956227+00:00', '--job-id', '20', '--raw', '--subdir', '/Users/yellow/Desktop/data_engineering/airflow_weather_01/dags/dag_weather.py', '--cfg-path', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmpt_n66tqf', '--error-file', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmpcv03_6k4']
[2025-03-17 13:00:33,833] {standard_task_runner.py:77} INFO - Job 20: Subtask load_data
[2025-03-17 13:00:33,871] {logging_mixin.py:109} INFO - Running <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T11:59:24.956227+00:00 [running]> on host 147.0.168.192.in-addr.arpa
[2025-03-17 13:00:33,907] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=weather_ingestion
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2025-03-17T11:59:24.956227+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-17T11:59:24.956227+00:00
[2025-03-17 13:00:33,959] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-17 13:00:33,960] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-03-17 13:00:33,960] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-03-17 13:00:33,971] {python.py:152} INFO - Done. Returned value was: None
[2025-03-17 13:00:33,977] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=weather_ingestion, task_id=load_data, execution_date=20250317T115924, start_date=20250317T120033, end_date=20250317T120033
[2025-03-17 13:00:34,021] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-03-17 13:00:34,039] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
